@startuml
!include <c4/C4_Container.puml> 
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome
!include DEVICONS/react.puml
!include DEVICONS2/fastapi.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/database.puml
!include DEVICONS2/jupyter.puml
!include FONTAWESOME/map.puml
!include FONTAWESOME/rub.puml
!include FONTAWESOME/vk.puml

LAYOUT_WITH_LEGEND()

Person(user, "Пользователь")
System_Boundary(c1, "Система поддержки принятия решений в региональном финансировании") {
    Container(web_frontend, "Single Page Application", "React", "Frontend-приложение, проведение аналитики, интерпретация результатов", "react")
    Container(web_api, "API", "FastAPI", "Backend-приложение, API", "fastapi")
    Container(information_collector, "Data Collection", "API, Parsing", "Модуль сбора данных из соцсетей", "database")
    ContainerDb(no_sql, "Raw Data Storage", "MongoDB", "Хранилище необработанных данных", "mongodb")
    Container(data_cleaner, "Data Cleaning", "Tokenization, Stemming, Lemmatization", "Модуль очистки данных и подготовки к анализу", "jupyter")
    ContainerDb(sql_db, "Data Storage", "Postgres", "Хранилище обработанных данных, результатов аналитики, информации пользователей", "postgresql")
    Container(data_analysis, "Data Analysis", "NLP methods, Machine Learning", "Модуль анализа данных и идентификации ключевых проблем", "jupyter")
    Container(qgis, "Geographic Information System", "QGIS", "Геоинформационная система для визуальной интерпретации результатов", "map")
    Container(finance, "Financial Decision Making Module", "Алгоритмы оптимизации и методы многокритериального принятия решений", "Модуль принятия финансовых решений", "rub")
}
System_Ext(social_media, "Social Networks", "VK, Telegram", "vk")
Rel(user, web_frontend, "")
Rel(web_frontend, web_api, "", "")
Rel(web_api, information_collector, "", "")
Rel_R(information_collector, data_cleaner, "", "")
Rel_L(information_collector, social_media, "", "")
Rel_R(information_collector, no_sql, "", "")
Rel_L(data_cleaner, no_sql, "", "")
Rel_U(data_cleaner, sql_db, "", "")
Rel_U(web_api, data_analysis, "", "")
Rel(data_analysis, sql_db, "", "")
Rel_U(web_api, qgis, "", "")
Rel(qgis, sql_db, "", "")
Rel_L(web_api, finance, "", "")
Rel(finance, sql_db, "", "")
@enduml