@startuml ""

actor Аналитик as Analyst

Analyst --> (Авторизоваться)

Analyst -left-> (Собрать данные)
(Собрать данные) <.. (Отменить сбор) : <<extends>>
(Настроить параметры сбора) <.. (Собрать данные) : <<includes>>

Analyst -right-> (Определить ключевые проблемы)
(Определить ключевые проблемы) ..> (Настроить параметры\nочистки данных) : <<includes>>
(Определить ключевые проблемы) ..> (Настроить параметры\nтематик) : <<includes>>
(Определить ключевые проблемы) <.right. (Отменить анализ) : <<extends>>

Analyst -up-> (Получить финансовые\nрекомендации)
(Получить финансовые\nрекомендации) .right.> (Настроить параметры\nбюджета и приоритетов) : <<includes>>
(Получить финансовые\nрекомендации) <.up. (Скорректировать рекомендации) : <<extends>>

Analyst --> (Получить результаты)
(Получить результаты) <.. (Ознакомиться с виузализацией) : <<extends>>
(Получить результаты) <.. (Экспортировать отчетность) : <<extends>>

actor Администратор as Admin
Admin -up-> (Авторизоваться)
Admin -right-> (Управлять пользователями)
Admin --> (Настраивать глобальные\nпараметры системы)

@enduml